services:
  - type: web
    name: streamvault-api
    runtime: node
    plan: free
    buildCommand: curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o ./yt-dlp && chmod +x ./yt-dlp && ./yt-dlp --version && pnpm install && pnpm --filter @workspace/api-server run build
    startCommand: node --enable-source-maps ./artifacts/api-server/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        sync: false
      - key: YT_DLP_PATH
        value: /opt/render/project/src/yt-dlp
    healthCheckPath: /api/healthz
    autoDeploy: true
